project:
  type: website
  output-dir: docs

website:
  title: "propertax"
  navbar:
    background: primary
    left:
      - href: about.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css



