project:
  type: website
  
website:
  title: "Land Value Taxes solve all your problems"
  navbar:
    background: primary
    left:
      - href: about.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: pulse
    css: styles.css



